#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GHIDRA=/opt/ghidra/support/analyzeHeadless
PROJ="$ROOT/ghidra_proj"
OUT="$ROOT/build"

# Two modes.
#
#   (no argument)   full run: re-exports functions.json, string_pointers.json
#                   and branches.json and COPIES them over the committed files
#                   in data/.
#   --decomp-only   refresh build/decomp/ only. Writes nothing under data/ and
#                   does not even run DumpImmediates/EnumerateBranches.
#
# The split is not a convenience. data/functions.json, data/branches.json and
# data/string_pointers.json are committed, and the port's branch-coverage
# baseline is measured against them: a run whose purpose was to refresh a
# gitignored build artifact must not be able to move that baseline as a side
# effect. The five oracles under data/ are never regenerated by either mode.
DECOMP_ONLY=0
case "${1-}" in
  --decomp-only) DECOMP_ONLY=1 ;;
  "") ;;
  *) echo "usage: $0 [--decomp-only]" >&2; exit 2 ;;
esac

mkdir -p "$PROJ" "$OUT"

if [ ! -d "$PROJ/gopnik.rep" ]; then
  "$GHIDRA" "$PROJ" gopnik -import "$ROOT/orig/g.exe" -analysisTimeoutPerFile 600
fi

if [ "$DECOMP_ONLY" = 1 ]; then
  "$GHIDRA" "$PROJ" gopnik -process g.exe -noanalysis \
    -scriptPath "$ROOT/tools/ghidra" \
    -postScript ExportAll.java "$OUT" decomp-only
  echo "decomp files: $(ls "$OUT/decomp" | wc -l)"
  echo "decomp-only: data/ untouched"
  exit 0
fi

"$GHIDRA" "$PROJ" gopnik -process g.exe -noanalysis \
  -scriptPath "$ROOT/tools/ghidra" \
  -postScript ExportAll.java "$OUT" full \
  -postScript DumpImmediates.java "$OUT" "$ROOT/orig/g.exe" \
  -postScript EnumerateBranches.java "$OUT" "$ROOT"

cp "$OUT/functions.json" "$ROOT/data/functions.json"
cp "$OUT/string_pointers.json" "$ROOT/data/string_pointers.json"
cp "$OUT/string_pointers_audit.tsv" "$ROOT/data/string_pointers_audit.tsv"
cp "$OUT/branches.json" "$ROOT/data/branches.json"
echo "decomp files: $(ls "$OUT/decomp" | wc -l)"
